-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS staging.customers
(
    customer_id integer NOT NULL,
    first_name character varying(40) NOT NULL,
    last_name character varying(40) NOT NULL,
    phone character varying(25),
    email character varying(50) NOT NULL,
    street character varying(255),
    city character varying(50),
    state character varying(25),
    zip_code character varying(5),
    PRIMARY KEY (customer_id)
);

COMMENT ON TABLE staging.customers
    IS 'The  sales.customers table stores customer’s information including first name, last name, phone, email, street, city, state and zip code.';

CREATE TABLE IF NOT EXISTS staging.staffs
(
    staff_id integer NOT NULL,
    first_name character varying(40) NOT NULL,
    last_name character varying(40) NOT NULL,
    email character varying(255) NOT NULL,
    phone character varying(25),
    active smallint NOT NULL,
    store_id integer NOT NULL,
    manager_id integer,
    PRIMARY KEY (staff_id)
);

COMMENT ON TABLE staging.staffs
    IS 'The  sales.staffs table stores the essential information of staffs including first name, last name. It also contains the communication information such as email and phone.';

CREATE TABLE IF NOT EXISTS staging.orders
(
    order_id integer NOT NULL,
    customer_id integer,
    order_status smallint NOT NULL,
    order_date date NOT NULL,
    required_date date NOT NULL,
    shipped_date date,
    store_id integer NOT NULL,
    staff_id integer NOT NULL,
    CONSTRAINT pk_order_id PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS staging.stores
(
    store_id integer NOT NULL,
    store_name character varying(255) NOT NULL,
    phone character varying(25),
    email character varying(255),
    street character varying(255),
    city character varying(255),
    state character varying(25),
    zip_code character varying(5),
    PRIMARY KEY (store_id)
);

CREATE TABLE IF NOT EXISTS staging.order_items
(
    order_id integer,
    item_id integer,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    list_price numeric(10, 2) NOT NULL,
    discount numeric(4, 2) NOT NULL DEFAULT 0,
    PRIMARY KEY (order_id, item_id)
);

CREATE TABLE IF NOT EXISTS staging.categories
(
    category_id integer NOT NULL,
    category_name character varying(255) NOT NULL,
    PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS staging.products
(
    product_id integer NOT NULL,
    product_name character varying(255) NOT NULL,
    brand_id smallint NOT NULL,
    category_id smallint NOT NULL,
    model_year smallint NOT NULL,
    list_price numeric(10, 2) NOT NULL,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS staging.stocks
(
    store_id integer,
    product_id integer,
    quantity integer,
    PRIMARY KEY (store_id, product_id)
);

COMMENT ON TABLE staging.stocks
    IS 'The production.stocks table stores the inventory information i.e. the quantity of a particular product in a specific store.';

CREATE TABLE IF NOT EXISTS staging.brands
(
    brand_id integer NOT NULL,
    brand_name character varying(255) NOT NULL,
    PRIMARY KEY (brand_id)
);
END;
